modLoader="javafml"
loaderVersion="[40,)"
license="WTF"

[[mods]]
modId="hukuta_item_pack"
version="0.0.1"
displayName="Hu4uTa Item Pack"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="hu4uta"

[[dependencies.hukuta_item_pack]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




